lapulpeta/Nostrid

Nostrid/Data/AccountService.cs
Nostrid/Data/EventDatabase.cs
Nostrid/Data/FeedService.cs

Removed db transactions

---

Nostrid/Data/RelayService.cs
Nostrid/Data/Relays/SubscriptionFilter.cs
Nostrid/Model/Event.cs
Nostrid/Pages/Notes.razor
Nostrid/Shared/FeedViewer.razor

Accelerated loading of account details

---

Nostrid.Core/Misc/ByteTools.cs
Nostrid.Core/Pages/Accounts.razor
README.md

Added support for nsec

---

Nostrid.Core/Data/EventDatabase.cs
Nostrid.Core/Data/FeedService.cs
Nostrid.Core/Shared/NavMenu.razor

Mentions count in menu toggle button

---

Nostrid.Core/Data/AccountService.cs
Nostrid.Core/Data/FeedService.cs
Nostrid.Core/Data/Nip05Service.cs
Nostrid.Core/Model/AccountDetails.cs
Nostrid.Core/Model/Nip05Data.cs
Nostrid.Core/Model/NoteTree.cs
Nostrid.Core/Pages/AccountPage.razor
Nostrid.Core/Pages/Accounts.razor
Nostrid.Core/Pages/Notes.razor
Nostrid.Core/Shared/AccountName.razor
Nostrid.Core/Shared/AccountPicture.razor
Nostrid.Core/Shared/FeedViewer.razor
Nostrid.Core/Shared/FollowAccount.razor
Nostrid.Core/Shared/NavMenu.razor
Nostrid.Core/Shared/NoteComposer.razor
Nostrid.Core/Shared/NoteViewer.razor
Nostrid.Web/Program.cs
Nostrid/MauiProgram.cs

Added support for NIP-05

---

Nostrid.Core/Data/AccountService.cs
Nostrid.Core/Data/NotificationService.cs
Nostrid.Core/Shared/NavMenu.razor
Nostrid/MauiProgram.cs
Nostrid/Misc/DbConstants.cs
Nostrid/Misc/NotificationCounterForMobile.cs
Nostrid/Nostrid.csproj
Nostrid/Platforms/Android/AndroidManifest.xml
Nostrid/Platforms/Android/NotificationCounter.cs
Nostrid/Platforms/MacCatalyst/NotificationCounter.cs
Nostrid/Platforms/Windows/NotificationCounter.cs
Nostrid/Platforms/iOS/NotificationCounter.cs

Added unread notification

---

Nostrid.Core/Data/FeedService.cs
Nostrid.Core/Shared/NoteViewer.razor

Fixed reposts not appearing

---

Nostrid.Core/Data/AccountService.cs
Nostrid.Core/Data/FeedService.cs
Nostrid.Core/Data/ISigner.cs
Nostrid.Core/Data/LocalSigner.cs
Nostrid.Core/Model/Account.cs
Nostrid.Core/Pages/AccountPage.razor
Nostrid.Core/Pages/Accounts.razor
Nostrid.Core/Shared/FollowAccount.razor
Nostrid.Core/Shared/MainLayout.razor
Nostrid.Core/Shared/NoteComposer.razor
Nostrid.Core/Shared/NoteViewer.razor
Nostrid.Web/ExtensionSigner.cs
Nostrid.Web/Program.cs
Nostrid.Web/wwwroot/signer.js

Added support for nos2x extension

---

Nostrid.Core/Data/EventDatabase.cs
Nostrid.Core/Model/IdType.cs
Nostrid.Core/Shared/ConfirmationModal.razor
Nostrid.Core/Shared/Navigator.razor

Added hex type selector in explore page

---

Nostrid.Core/Externals/IMediaService.cs
Nostrid.Core/Externals/NostrBuildMediaService.cs
Nostrid.Core/Externals/VoidCatMediaService.cs
Nostrid.Core/Misc/ProgressStream.cs
Nostrid.Core/Shared/Alert.razor
Nostrid.Core/Shared/MainLayout.razor
Nostrid.Core/Shared/NoteComposer.razor

52 upload progress

---

Nostrid.Core/Pages/AccountPage.razor
Nostrid.Core/Pages/Notes.razor
Nostrid.Core/Shared/NoteViewer.razor

55 add copy menu

---

Nostrid.Core/Data/EventDatabase.cs
Nostrid.Core/Data/FeedService.cs
Nostrid.Core/Data/RelayService.cs
Nostrid.Core/Migrations/20230128154625_ManualRelayManagement.Designer.cs
Nostrid.Core/Migrations/20230128154625_ManualRelayManagement.cs
Nostrid.Core/Model/Database/Config.cs
Nostrid.Core/Model/Database/Relay.cs
Nostrid.Core/Pages/Accounts.razor
Nostrid.Core/Pages/ConfigPage.razor
Nostrid.Core/Shared/NavMenu.razor

Manual relay management

---

Nostrid.Core/Data/RelayService.cs
Nostrid.Core/Data/Relays/SubscriptionFilter.cs
Nostrid.Core/Data/Relays/TagSubscriptionFilter.cs
Nostrid.Core/Model/Database/Relay.cs
Nostrid.Core/Model/Nip11Response.cs

Add support for NIP-11

---

Nostrid.Core/Pages/AccountPage.razor
Nostrid.Core/Shared/FollowsCounter.razor

Throttled refresh

---

Nostrid.Core/Data/EventDatabase.cs
Nostrid.Core/Data/RelayService.cs
Nostrid.Core/Data/Relays/SubscriptionFilter.cs
Nostrid.Core/Pages/AccountPage.razor

Added option to reload follows

---

Nostrid.Core/Data/EventDatabase.cs
Nostrid.Core/Data/FeedService.cs
Nostrid.Core/Model/NoteTree.cs
Nostrid.Core/Model/NoteTreeShowMore.cs
Nostrid.Core/Pages/Notes.razor
Nostrid.Core/Shared/FeedViewer.razor
Nostrid.Core/Shared/NoteTreeViewer.razor
Nostrid.Core/Shared/NoteViewer.razor
Nostrid.Core/Shared/NoteViewerSeeMore.razor

Improved visualization of long threads

---

NNostr.Client/NostrClient.cs
Nostrid.Core/Data/ConfigService.cs
Nostrid.Core/Data/RelayService.cs
Nostrid.Core/Migrations/20230208180012_RelayFilters.Designer.cs
Nostrid.Core/Migrations/20230208180012_RelayFilters.cs
Nostrid.Core/Misc/Utils.cs
Nostrid.Core/Model/Database/Config.cs
Nostrid.Core/Pages/ConfigPage.razor
Nostrid.Core/Shared/ConfigSection.razor

Added support for proxies

---

Nostrid.Core/Main.razor
Nostrid.Core/Pages/AccountPage.razor
Nostrid.Core/Pages/ChannelViewer.razor
Nostrid.Core/Pages/FollowsFeed.razor
Nostrid.Core/Pages/GlobalFeed.razor
Nostrid.Core/Pages/HashtagFeed.razor
Nostrid.Core/Pages/MentionsFeed.razor
Nostrid.Core/Pages/SavedFeed.razor
Nostrid.Core/Shared/ElementObserver.razor
Nostrid.Core/Shared/FeedViewer.razor
Nostrid.Core/Shared/Scripts.razor
Nostrid.Web/wwwroot/css/app.css
Nostrid.Web/wwwroot/scripts.js
Nostrid/wwwroot/css/app.css
Nostrid/wwwroot/scripts.js

Implemented infinite scroll

---

Nostrid.Core/Pages/ConfigPage.razor
Nostrid.Core/Shared/ElementObserver.razor
Nostrid.Core/Shared/FeedViewer.razor
Nostrid.Core/Shared/MainLayout.razor
Nostrid.Core/Shared/MessageWrapperViewer.razor
Nostrid.Core/Shared/ModalContainer.razor
Nostrid.Core/Shared/NavMenu.razor
Nostrid.Core/Shared/NoteViewer.razor
Nostrid.Core/Shared/PayModal.razor
Nostrid.Core/Shared/Scripts.razor

Script component as cascading parameter

---

Nostrid.Core/Data/FeedService.cs

Fix: LastNotificationRead Exception reading the date when creating a new account
Closes #82

Fix: LastNotificationRead Exception

---

Nostrid.Core/Pages/Favorites.razor
Nostrid.Core/Pages/Feed.razor
Nostrid.Core/Pages/HashtagFeed.razor
Nostrid.Core/Pages/Home.razor
Nostrid.Core/Pages/SavedFeed.razor
Nostrid.Core/Shared/FeedViewer.razor
Nostrid.Core/Shared/FollowsFeed.razor
Nostrid.Core/Shared/GlobalFeed.razor
Nostrid.Core/Shared/MentionsFeed.razor
Nostrid.Core/Shared/NavMenu.razor
Nostrid.Core/Shared/NavMenu.razor.css
Nostrid.Core/Shared/NoteViewer.razor
Nostrid.Core/Shared/NoteViewerSeeMore.razor
Nostrid.Web/wwwroot/css/app.css
Nostrid.Web/wwwroot/scripts.js
Nostrid/wwwroot/css/app.css
Nostrid/wwwroot/scripts.js

Joined global, following and mentions feed
Refresh button update

Menu icons

---

Nostrid.Core/Pages/FollowsEdit.razor

99 import follows

---

Nostrid.Core/Pages/FollowsEdit.razor
Nostrid.Photino/wwwroot/scripts.js
Nostrid.Web/wwwroot/scripts.js
Nostrid/wwwroot/scripts.js

Export follows feature

---

Nostrid.Core/Model/NoteTree.cs
Nostrid.Core/Pages/Notes.razor
Nostrid.Core/Shared/MessageWrapperViewer.razor
Nostrid.Core/Shared/NoteTreeViewer.razor
Nostrid.Core/Shared/NoteViewer.razor
Nostrid.Core/Shared/PayButton.razor

Improved rendering notes

---

Nostrid.Core/Externals/NostrcheckMediaService.cs
Nostrid.Photino/Program.cs
Nostrid.Web/Program.cs
Nostrid/MauiProgram.cs

Implemented nostrcheck

---

Nostrid.Core/Data/NoteProcessor.cs
Nostrid.Core/Shared/EventViewer.razor
Nostrid.Core/Shared/FollowAccount.razor
Nostrid.Core/Shared/MessageViewer.razor
Nostrid.Core/Shared/NavMenu.razor
Nostrid.Core/Shared/NoteComposer.razor
Nostrid.Core/Shared/NoteViewer.razor
Nostrid.Photino/wwwroot/css/app.css
Nostrid.Web/wwwroot/css/app.css
Nostrid/wwwroot/css/app.css

109 noteprocessor accountname

---

Nostrid.Core/Data/EventDatabase.cs
Nostrid.Core/Shared/ConfirmationModal.razor
Nostrid.Core/Shared/FollowButton.razor
Nostrid/wwwroot/css/app.css

98 show warning

---

Nostrid.Core/Data/EventDatabase.cs
Nostrid.Core/Shared/NoteViewer.razor
Nostrid.Core/Shared/ReactionsPopup.razor
Nostrid.sln

91 reaction list

---

Nostrid.Core/Data/NotificationService.cs
Nostrid.Core/Shared/EventViewer.razor
Nostrid.Core/Shared/MessageWrapperViewer.razor
Nostrid.Core/Shared/TimeStamp.razor

Added timer to update timestamp periodically

---

Nostrid.Core/Model/Database/Event.cs
Nostrid.Core/Pages/AccountPage.razor
Nostrid.Core/Pages/Accounts.razor
Nostrid.Core/Pages/DmList.razor
Nostrid.Core/Pages/FollowsEdit.razor
Nostrid.Core/Shared/AccountName.razor
Nostrid.Core/Shared/AccountPicture.razor
Nostrid.Core/Shared/EventViewer.razor
Nostrid.Core/Shared/MessageViewer.razor
Nostrid.Core/Shared/PayButton.razor
Nostrid.Core/Shared/PayModal.razor

Improve account details handling
